[FIX] motion_module.py, error: missing encoder_hidden_states (#205)
* [FIX] motion_module.py, error: missing encoder_hidden_states

I fixed this error:
```
TypeError: VanillaTemporalModule.forward() missing 1 required positional argument: 'encoder_hidden_states'
```
With this fix this error won't happen again.

* edit

---------

Co-authored-by: Chengsong Zhang <continuerevolution@gmail.com>